#!/usr/bin/env python3
"""Generate card/banner previews without changing the original project photos.

Run from any directory with Python 3, Pillow, and Node installed:
    python3 scripts/generate-responsive-photos.py
The site build uses the checked-in previews; Python is not a build dependency.
"""

import json
from pathlib import Path
import subprocess

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "images" / "responsive"
HELPER = ROOT / "src" / "responsive-photos.js"
WIDTHS = (480, 800)

# Keep this selection in step with the actual page cards. Album photos beyond
# their cover are deliberately omitted; lightboxes retain the original files.
PHOTO_SELECTION = r"""
import { business, services, servicesPageServices, projects } from './src/data.js';
const sources = new Set([
  '/images/hero-sharp.webp',
  '/images/services-hero.webp',
  '/images/marking-job.webp',
]);
const sourceFor = s => s.homeImage || s.image;
for (const service of services) {
  sources.add(service.homepageCards?.service?.src || service.homepageImage || sourceFor(service));
}
for (const project of projects.filter(p => p.images?.length)) {
  sources.add(project.images[0].src);
  const service = services.find(s => s.id === project.category);
  if (!service) continue;
  const linked = projects.find(p => (service.projectId ? p.id === service.projectId : p.category === service.id) && p.images?.length);
  sources.add(project.homepagePhoto?.src || (linked?.id === project.id
    ? service.homepageCards?.project?.src || service.homepageImage || sourceFor(service)
    : project.images[0].src));
}
for (const service of servicesPageServices) {
  sources.add(service.servicesPageImage?.src || sourceFor(service));
}
sources.add(business.contactPhotos.main.src);
business.contactPhotos.info.forEach(photo => sources.add(photo.src));
console.log(JSON.stringify([...sources].sort()));
"""

HELPER_FUNCTION = r'''
const escapeAttribute = value => String(value).replace(/[&<>"']/g, character => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[character]);

/**
 * Return optional HTML attributes for static cards and secondary page banners.
 * Keep the original src/width/height on the img; do not use this for lightboxes
 * or the homepage slider, which have their own full-photo behavior.
 */
export function responsivePhotoAttributes(src, sizes = '(min-width: 1304px) 580px, (min-width: 761px) calc((100vw - 96px) / 2), calc(100vw - 32px)', base = '/') {
  const photo = responsivePhotos[src];
  if (!photo) return '';
  const prefix = base.endsWith('/') ? base : `${base}/`;
  const stem = src.slice('/images/'.length).replace(/\.webp$/, '');
  const candidates = photo.widths.map(width => `${prefix}images/responsive/${stem}-${width}.webp ${width}w`);
  candidates.push(`${prefix}${src.replace(/^\//, '')} ${photo.originalWidth}w`);
  return `srcset="${escapeAttribute(candidates.join(', '))}" sizes="${escapeAttribute(sizes)}"`;
}
'''


def main():
    sources = json.loads(subprocess.check_output(
        ["node", "--input-type=module", "-e", PHOTO_SELECTION], cwd=ROOT, text=True
    ))
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    original_bytes = 0
    variant_bytes = {width: 0 for width in WIDTHS}
    for src in sources:
        source = PUBLIC / src.lstrip("/")
        original_bytes += source.stat().st_size
        with Image.open(source) as raw:
            photo = ImageOps.exif_transpose(raw).convert("RGB")
            widths = [width for width in WIDTHS if width < photo.width]
            manifest[src] = {"originalWidth": photo.width, "widths": widths}
            for width in widths:
                height = round(photo.height * width / photo.width)
                preview = photo.resize((width, height), Image.Resampling.LANCZOS)
                target = OUTPUT / f"{source.stem}-{width}.webp"
                preview.save(target, format="WEBP", quality=88, method=6)
                variant_bytes[width] += target.stat().st_size
    HELPER.write_text(
        "// Generated by scripts/generate-responsive-photos.py; original photos are preserved.\n"
        + "export const responsivePhotos = " + json.dumps(manifest, indent=2) + ";\n"
        + HELPER_FUNCTION,
        encoding="utf-8",
    )
    print(json.dumps({
        "photos": len(manifest), "originalBytes": original_bytes,
        "previewBytesByWidth": variant_bytes,
        "savedPercentByWidth": {str(width): round(100 * (1 - size / original_bytes), 1)
                                for width, size in variant_bytes.items()},
    }, indent=2))


if __name__ == "__main__":
    main()
