#!/usr/bin/env python3
"""Generate small album previews without modifying the original photographs.

Run with Python 3, Pillow, and Node.js:
    python3 scripts/generate-gallery-thumbnails.py
The build uses checked-in previews; Python and Pillow are not build dependencies.
"""

import hashlib
import json
from pathlib import Path
import subprocess

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "images" / "thumbnails"
MANIFEST = ROOT / "src" / "gallery-thumbnail-photos.js"
WIDTH = 160
QUALITY = 65
PHOTO_SELECTION = """
import { projects } from './src/data.js';
console.log(JSON.stringify([...new Set(projects.flatMap(project =>
  (project.images || []).map(photo => photo.src)
))].sort()));
"""


def main():
    sources = json.loads(subprocess.check_output(
        ["node", "--input-type=module", "-e", PHOTO_SELECTION],
        cwd=ROOT, text=True,
    ))
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    sizes = []
    original_bytes = 0
    filenames = set()
    for src in sources:
        source = (PUBLIC / src.lstrip("/")).resolve()
        if not source.is_relative_to(PUBLIC.resolve()):
            raise ValueError(f"Photo must be within public/: {src}")
        filename = f"{source.stem}.webp"
        if filename in filenames:
            raise ValueError(f"Thumbnail filenames must be unique: {filename}")
        filenames.add(filename)
        original = source.read_bytes()
        original_bytes += len(original)
        original_hash = hashlib.sha256(original).digest()
        with Image.open(source) as raw:
            photo = ImageOps.exif_transpose(raw).convert("RGB")
            width = min(WIDTH, photo.width)
            height = round(photo.height * width / photo.width)
            preview = photo.resize((width, height), Image.Resampling.LANCZOS)
            target = OUTPUT / filename
            preview.save(target, format="WEBP", quality=QUALITY, method=6)
            sizes.append(target.stat().st_size)
            manifest[src] = f"/images/thumbnails/{filename}"
        if hashlib.sha256(source.read_bytes()).digest() != original_hash:
            raise RuntimeError(f"Original photograph changed: {src}")
    MANIFEST.write_text(
        "// Generated by scripts/generate-gallery-thumbnails.py; original photos are preserved.\n"
        + "export const galleryThumbnailPhotos = "
        + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(json.dumps({
        "photos": len(manifest),
        "width": WIDTH,
        "quality": QUALITY,
        "originalBytes": original_bytes,
        "thumbnailBytes": sum(sizes),
        "smallestThumbnailBytes": min(sizes, default=0),
        "largestThumbnailBytes": max(sizes, default=0),
        "originalsUnchanged": True,
    }, indent=2))


if __name__ == "__main__":
    main()
