// แก้ข้อมูลธุรกิจและช่องทางติดต่อที่นี่ก่อนเผยแพร่จริง
export const business = {
  name: 'TRS TAMRONGSAK', thaiName: 'ทีอาร์เอส ธำรงศักดิ์ คอนสตรัคชั่น',
  phone: '062-248-4089', // เช่น 0812345678
  lineId: '@138wlldt', lineUrl: 'https://line.me/ti/p/%40138wlldt', // เช่น https://line.me/ti/p/~your-id
  email: 'tamrong2519@gmail.com',
  address: 'หมู่บ้าน อาร์เคปาร์ค หทัยราษฎร์ แขวงบางชัน เขตคลองสามวา กรุงเทพมหานคร 10510',
  mapLocation: 'หมู่บ้าน อาร์เคปาร์ค หทัยราษฎร์',
  serviceArea: 'กรุงเทพฯ และปริมณฑล • ชลบุรี • ระยอง • ฉะเชิงเทรา',
  siteUrl: 'https://www.trsasphalt.com/', // โดเมนหลักของเว็บไซต์
  hours: 'กรุณาติดต่อเพื่อสอบถามเวลาทำการ',
  contactPhotos: {
    main: { src: '/images/contact-main.webp', alt: 'ภาพหน้างานรถบดบดอัดถนนลาดยางมะตอยข้างแนวต้นไม้', width: 960, height: 1280 },
    info: [
      { src: '/images/contact-asphalt.webp', alt: 'ภาพหน้างานลานลาดยางมะตอยและรถบดบริเวณอาคาร', width: 1280, height: 960 },
      { src: '/images/contact-gravel.webp', alt: 'ภาพหน้างานลานหินคลุกรอบอาคารและแนวต้นไม้', width: 1280, height: 960 },
      { src: '/images/contact-marking.webp', alt: 'ภาพหน้างานตีเส้นช่องจอดรถระหว่างอาคาร', width: 1280, height: 960 },
    ],
  },
};
export const services = [
  { id: 'asphalt', homepageCards: {
    service: { src: '/images/asphalt-job-18.webp', alt: 'ภาพหน้างานทีมงานและเครื่องปูยางมะตอยบริเวณลานโรงเรียน', width: 1280, height: 960 },
    project: { src: '/images/asphalt-job-17.webp', alt: 'ภาพหน้างานลาดยางมะตอยและเครื่องปูยางข้างอาคารโรงเรียน', width: 960, height: 1280 },
  }, servicesPageImage: { src: '/images/services-asphalt.webp', alt: 'ภาพหน้างานรถบดบดอัดผิวลาดยางมะตอยระหว่างแนวต้นไม้', width: 1280, height: 720 }, number: '01', title: 'ลาดยางมะตอย', subtitle: 'ปูยางแอสฟัลท์', scene: 0, image: '/images/hero-daylight.webp', description: 'ปูยางแอสฟัลท์สำหรับถนนและลานจอดรถ', details: ['สำรวจสภาพพื้นที่และระดับผิวทาง', 'วางแผนเตรียมพื้นและการระบายน้ำ', 'ปูยางแอสฟัลท์และบดอัดผิวทาง'] },
  { id: 'gravel', homepageCards: {
    service: { src: '/images/home-gravel-service.webp', alt: 'ภาพหน้างานลานหินคลุกข้างอาคารสีน้ำเงิน', width: 1280, height: 960 },
    project: { src: '/images/gravel-job-14.webp', alt: 'ภาพหน้างานลานจอดรถหินคลุกระหว่างอาคารและกำแพง', width: 1280, height: 960 },
  }, servicesPageImage: { src: '/images/services-gravel.webp', alt: 'ภาพหน้างานลานหินคลุกและรถขุดบริเวณอาคาร', width: 1280, height: 960 }, slideImage: '/images/gravel-slide.webp', homeImage: '/images/gravel-job.webp', number: '02', title: 'ลานจอดรถหินคลุก', subtitle: 'เกลี่ยและบดอัดหินคลุก', scene: 1, image: '/images/work-scenes.webp', description: 'เกลี่ยและบดอัดหินคลุก สำหรับลานจอดรถและทางเข้าออก', details: ['ประเมินระดับและสภาพพื้นเดิม', 'เลือกวัสดุให้เหมาะกับการใช้งาน', 'เกลี่ยปรับระดับและบดอัดพื้นที่'] },
  { id: 'stone', homeImage: '/images/stone-job.webp', number: '03', title: 'งานหินเกล็ด', subtitle: 'ปรับพื้นที่และทางเข้าออก', scene: 2, image: '/images/work-scenes.webp', description: 'ปรับพื้นด้วยหินเกล็ด สำหรับลานและพื้นที่ใช้งาน', details: ['สำรวจสภาพพื้นเดิม', 'วางแผนวัสดุและระดับพื้นที่', 'เกลี่ยและบดอัดให้เหมาะกับงาน'] },
  { id: 'speed-bump', servicesPageImage: { src: '/images/services-speed-bump.webp', alt: 'ภาพหน้างานลูกระนาดยางมะตอยสีส้มขาวบริเวณถนนหน้าอาคาร', width: 1280, height: 960 }, homeImage: '/images/speed-bump-job.webp', number: '04', title: 'ลูกระนาดยางมะตอย', subtitle: 'ชะลอความเร็วในพื้นที่', scene: 3, image: '/images/work-scenes.webp', description: 'ทำลูกระนาดยางมะตอย เพื่อชะลอความเร็วในพื้นที่', details: ['สำรวจตำแหน่งติดตั้ง', 'กำหนดรูปแบบตามการใช้งาน', 'จัดทำผิวและเครื่องหมายที่เหมาะสม'] },
  { id: 'marking', servicesPageImage: { src: '/images/services-marking.webp', alt: 'ภาพหน้างานทีมงานตีเส้นจราจรและลูกศรบอกทิศทางในลานจอดรถ', width: 1280, height: 960 }, homepageImage: '/images/marking-home.webp', homeImage: '/images/marking-job.webp', number: '05', title: 'ตีเส้นจราจร', subtitle: 'สีเทอร์โมพลาสติก', scene: 4, image: '/images/work-scenes.webp', description: 'ตีเส้นถนนและช่องจอดรถด้วยสีเทอร์โมพลาสติก', details: ['วางผังช่องจอดและเส้นจราจร', 'เตรียมผิวก่อนทำเครื่องหมาย', 'ตีเส้นด้วยสีเทอร์โมพลาสติก'] },
];
export const servicesPageServices = [
  ...services,
  {
    id: 'gravel-road', projectId: 'gravel-road', number: '06', title: 'ถนนหินคลุก บดอัด',
    subtitle: 'เกลี่ยปรับระดับและบดอัดถนน',
    servicesPageImage: { src: '/images/services-gravel-road.webp', alt: 'ภาพหน้างานทีมงาน รถขุด และรถบดขณะเกลี่ยและบดอัดถนนหินคลุกระหว่างอาคาร', width: 960, height: 1280 },
    description: 'เกลี่ยปรับระดับและบดอัดหินคลุก สำหรับถนนภายในโครงการและทางเข้าออก',
    details: ['สำรวจแนวถนนและระดับพื้นเดิม', 'เกลี่ยหินคลุกและปรับระดับตามแนวทาง', 'บดอัดผิวถนนให้แน่นและเก็บขอบทาง'],
  },
];
// 1 รายการ = 1 ชุดภาพ เพิ่มโครงการใหม่โดยคัดลอกรายการและเปลี่ยนข้อมูลจริง
// รูปแรกเป็นหน้าปก; location เว้นว่างได้; imageKind: 'illustration' ใช้กับภาพประกอบเท่านั้น
export const projects = [
  {
    id: 'asphalt-road', category: 'asphalt', title: 'งานลาดยางมะตอย',
    location: '', description: 'งานลาดยางมะตอยบริเวณถนนและทางเข้าอาคาร',
    siteTypes: 'ถนน ทางเข้าอาคาร ลานโรงเรียน และทางเดินในสวน',
    workScope: 'ปู เกลี่ย และบดอัดผิวลาดยางมะตอย',
    images: [
      { src: '/images/asphalt-job-01.webp', alt: 'ภาพหน้างานลาดยางมะตอยบริเวณถนนและทางเข้าอาคาร' },
      { src: '/images/asphalt-job-02.webp', alt: 'ภาพหน้างานลาดยางมะตอยและรถบดบริเวณอาคาร' },
      { src: '/images/asphalt-job-03.webp', alt: 'รถบดเก็บผิวลาดยางมะตอยข้างอาคาร' },
      { src: '/images/asphalt-job-04.webp', alt: 'งานบดอัดยางมะตอยบริเวณทางเข้าอาคาร' },
      { src: '/images/asphalt-job-05.webp', alt: 'งานลาดยางมะตอยบริเวณทางโค้งและลานอาคาร' },
      { src: '/images/asphalt-job-06.webp', alt: 'ผิวถนนลาดยางมะตอยและพื้นที่ทางเข้าอาคาร' },
      { src: '/images/asphalt-job-07.webp', alt: 'รายละเอียดผิวลาดยางมะตอยและขอบทาง' },
      { src: '/images/asphalt-job-08.webp', alt: 'ภาพรวมถนนลาดยางมะตอยบริเวณอาคาร' },
      { src: '/images/asphalt-job-09.webp', alt: 'ทีมงานและเครื่องจักรขณะปูยางมะตอย' },
      { src: '/images/asphalt-job-10.webp', alt: 'เครื่องปูยางมะตอยและรถบดขณะลาดยางถนนข้างอาคาร' },
      { src: '/images/asphalt-job-11.webp', alt: 'ทีมงานเกลี่ยและเก็บขอบผิวลาดยางมะตอยหน้าเครื่องปู' },
      { src: '/images/asphalt-job-12.webp', alt: 'รถบดบดอัดผิวลาดยางมะตอยข้างอาคารอิฐสีเหลือง' },
      { src: '/images/asphalt-job-13.webp', alt: 'งานลาดยางมะตอยและบดอัดบริเวณทางเข้าออกอาคาร' },
      { src: '/images/asphalt-job-14.webp', alt: 'ภาพรวมผิวถนนลาดยางมะตอยบริเวณหน้าอาคารหลังบดอัด' },
      { src: '/images/asphalt-job-15.webp', alt: 'ผิวถนนลาดยางมะตอยตามแนวรางระบายน้ำข้างอาคาร' },
      { src: '/images/asphalt-job-16.webp', alt: 'ภาพรวมถนนลาดยางมะตอยและทางเข้าออกอาคารหลังเก็บผิวทาง' },
      { src: '/images/asphalt-job-17.webp', alt: 'ทีมงานและเครื่องปูยางมะตอยขณะลาดยางถนนข้างอาคารเรียน' },
      { src: '/images/asphalt-job-18.webp', alt: 'ทีมงานลาดยางมะตอยใต้หลังคาบริเวณหน้าอาคารเรียน' },
      { src: '/images/asphalt-job-19.webp', alt: 'รถบรรทุกส่งยางมะตอยให้เครื่องปูและรถบดในลานโรงเรียน' },
      { src: '/images/asphalt-job-20.webp', alt: 'ผิวถนนลาดยางมะตอยและทีมงานเก็บผิวบริเวณหน้าอาคารเรียน' },
      { src: '/images/asphalt-job-21.webp', alt: 'รถบดบดอัดผิวลาดยางมะตอยบริเวณหน้าอาคารเรียน' },
      { src: '/images/asphalt-job-22.webp', alt: 'ภาพรวมผิวถนนลาดยางมะตอยและรถบดภายในโรงเรียน' },
      { src: '/images/asphalt-job-23.webp', alt: 'ผิวถนนลาดยางมะตอยข้างอาคารเรียนหลังบดอัด' },
      { src: '/images/asphalt-job-24.webp', alt: 'ภาพแนวตั้งของถนนลาดยางมะตอยและรถบดภายในโรงเรียน' },
      { src: '/images/asphalt-job-25.webp', alt: 'ถนนลาดยางมะตอยบริเวณทางโค้งข้างอาคารเรียน' },
      { src: '/images/asphalt-job-26.webp', alt: 'งานลาดยางมะตอยทางเดินในสวนและทีมงานขณะบดอัด' },
      { src: '/images/asphalt-job-27.webp', alt: 'ทางเดินลาดยางมะตอยโค้งรอบสนามหญ้าและต้นไม้' },
      { src: '/images/asphalt-job-28.webp', alt: 'ทางเดินลาดยางมะตอยตามแนวแปลงต้นไม้ในสวน' },
      { src: '/images/asphalt-job-29.webp', alt: 'ภาพรวมทางแยกของทางเดินลาดยางมะตอยในสวน' },
    ],
  },
  {
    id: 'gravel-yard', category: 'gravel', title: 'งานลานจอดรถหินคลุก',
    location: '', description: 'เกลี่ยและบดอัดพื้นลานสำหรับการใช้งาน',
    siteTypes: 'ลานจอดรถและทางเข้าออก',
    workScope: 'เตรียมพื้น เกลี่ยปรับระดับ และบดอัดหินคลุก',
    images: [
      { src: '/images/projects-gravel-cover.webp', alt: 'ภาพหน้างานลานจอดรถหินคลุกข้างอาคารและแนวต้นไม้', width: 1280, height: 720 },
      { src: '/images/gravel-job.webp', alt: 'ภาพหน้างานลานจอดรถหินคลุก' },
      { src: '/images/gravel-slide.webp', alt: 'เครื่องจักรเกลี่ยและปรับพื้นลานหินคลุก' },
      { src: '/images/gravel-job-03.webp', alt: 'รถบดบดอัดพื้นลานจอดรถหินคลุก' },
      { src: '/images/gravel-job-04.webp', alt: 'ภาพรวมพื้นลานจอดรถหินคลุกหลังบดอัด' },
      { src: '/images/gravel-job-05.webp', alt: 'ผิวหินคลุกและพื้นที่ลานจอดรถ' },
      { src: '/images/gravel-job-06.webp', alt: 'กองหินคลุกเตรียมเกลี่ยและบดอัดพื้นลาน' },
      { src: '/images/gravel-job-07.webp', alt: 'เตรียมวัสดุหินคลุกสำหรับลานจอดรถ' },
      { src: '/images/gravel-job-08.webp', alt: 'กองหินคลุกและพื้นที่ลานก่อนเกลี่ยปรับระดับ' },
      { src: '/images/gravel-job-09.webp', alt: 'ภาพแนวตั้งของวัสดุหินคลุกเตรียมปรับพื้นลาน' },
      { src: '/images/gravel-job-10.webp', alt: 'รถขุดเตรียมเกลี่ยหินคลุกในลานจอดรถ' },
      { src: '/images/gravel-job-11.webp', alt: 'เครื่องจักรเตรียมพื้นลานก่อนลงหินคลุก' },
      { src: '/images/gravel-job-12.webp', alt: 'รถบดบดอัดพื้นลานจอดรถหินคลุกระหว่างอาคาร' },
      { src: '/images/gravel-job-13.webp', alt: 'ภาพรวมลานจอดรถหินคลุกหลังเกลี่ยและบดอัด' },
      { src: '/images/gravel-job-14.webp', alt: 'พื้นลานจอดรถหินคลุกและพื้นที่จอดรถข้างอาคาร' },
      { src: '/images/gravel-job-15.webp', alt: 'ผิวหินคลุกบดอัดและรถบดบริเวณลานจอดรถ' },
      { src: '/images/gravel-job-16.webp', alt: 'พื้นลานจอดรถหินคลุกหลังบดอัดบริเวณทางเข้าออก' },
      { src: '/images/gravel-job-17.webp', alt: 'รถขุดเตรียมพื้นดินและวัสดุหินคลุกสำหรับลานจอดรถ' },
      { src: '/images/gravel-job-18.webp', alt: 'รถบดบดอัดพื้นดินก่อนลงหินคลุกในลานจอดรถ' },
      { src: '/images/gravel-job-19.webp', alt: 'ภาพรวมการเตรียมพื้นลานจอดรถและกองหินคลุกระหว่างอาคาร' },
    ],
  },
  {
    id: 'stone-yard', category: 'stone', title: 'งานหินเกล็ด',
    anchorAliases: ['stone-building-yard', 'stone-home-yard'],
    location: '', description: 'งานหินเกล็ดสำหรับลาน รอบอาคาร และรอบบ้าน',
    siteTypes: 'ลานรอบอาคารและรอบบ้าน',
    workScope: 'เกลี่ยและบดอัดพื้นหินเกล็ด',
    images: [
      { src: '/images/stone-home-01.webp', alt: 'ภาพหน้างานหินเกล็ดบริเวณหน้าบ้าน', width: 960, height: 1280 },
      { src: '/images/stone-job.webp', alt: 'ภาพหน้างานหินเกล็ด' },
      { src: '/images/stone-job-02.webp', alt: 'ภาพรวมลานหินเกล็ดบริเวณอาคาร' },
      { src: '/images/stone-job-03.webp', alt: 'ลานหินเกล็ดและพื้นที่ทางเข้าอาคาร' },
      { src: '/images/stone-job-04.webp', alt: 'ผิวลานหินเกล็ดและพื้นที่ใช้งาน' },
      { src: '/images/stone-job-05.webp', alt: 'งานหินเกล็ดรอบอาคารและแนวต้นไม้' },
      { src: '/images/stone-job-06.webp', alt: 'รถบดบดอัดพื้นลานหินเกล็ด' },
      { src: '/images/stone-building-01.webp', alt: 'ภาพหน้างานลานหินเกล็ดข้างอาคาร' },
      { src: '/images/stone-building-02.webp', alt: 'ลานหินเกล็ดรอบต้นไม้และแนวกำแพง' },
      { src: '/images/stone-building-03.webp', alt: 'พื้นหินเกล็ดบริเวณทางเดินข้างอาคาร' },
      { src: '/images/stone-building-04.webp', alt: 'ภาพรวมลานหินเกล็ดรอบอาคารและแนวต้นไม้' },
      { src: '/images/stone-home-02.webp', alt: 'พื้นหินเกล็ดรอบต้นไม้และทางเดินข้างบ้าน' },
      { src: '/images/stone-home-03.webp', alt: 'งานหินเกล็ดข้างบ้านและแนวกำแพง' },
      { src: '/images/stone-home-04.webp', alt: 'ลานหินเกล็ดบริเวณทางเข้าบ้าน' },
      { src: '/images/stone-home-05.webp', alt: 'พื้นหินเกล็ดตลอดแนวด้านข้างบ้าน' },
    ],
  },
  {
    id: 'speed-bump-work', category: 'speed-bump', title: 'งานลูกระนาดยางมะตอย',
    homepagePhoto: { src: '/images/speed-bump-job-02.webp', alt: 'ภาพหน้างานรถบดเดินตามข้างลูกระนาดยางมะตอยบริเวณอาคารและแนวต้นไม้', width: 960, height: 1280 },
    location: '', description: 'จัดทำลูกระนาดและเครื่องหมายชะลอความเร็ว',
    siteTypes: 'ถนนและทางเข้าออกอาคาร',
    workScope: 'ขึ้นรูป บดอัด และเก็บขอบลูกระนาดยางมะตอย',
    images: [
      { src: '/images/projects-speed-bump-cover.webp', alt: 'ภาพหน้างานทีมงานใช้รถบดเดินตามบดอัดลูกระนาดยางมะตอย', width: 1280, height: 1280, coverPosition: 'center top' },
      { src: '/images/speed-bump-job.webp', alt: 'ภาพหน้างานลูกระนาดยางมะตอย' },
      { src: '/images/speed-bump-job-02.webp', alt: 'รถบดบดอัดงานลูกระนาดยางมะตอย' },
      { src: '/images/speed-bump-job-03.webp', alt: 'ทีมงานเกลี่ยยางมะตอยสำหรับลูกระนาด' },
      { src: '/images/speed-bump-job-04.webp', alt: 'ผิวลูกระนาดยางมะตอยระหว่างเก็บงาน' },
      { src: '/images/speed-bump-job-05.webp', alt: 'งานปูและปรับผิวลูกระนาดยางมะตอย' },
      { src: '/images/speed-bump-job-06.webp', alt: 'ทีมงานทำเครื่องหมายบนลูกระนาดยางมะตอย' },
      { src: '/images/speed-bump-job-07.webp', alt: 'ภาพรวมงานทำลูกระนาดยางมะตอยและเครื่องหมายชะลอความเร็ว' },
      { src: '/images/speed-bump-job-08.webp', alt: 'งานลูกระนาดยางมะตอยบริเวณทางเข้าอาคาร' },
      { src: '/images/speed-bump-job-09.webp', alt: 'ทีมงานขึ้นรูปและบดอัดลูกระนาดยางมะตอยบนถนนคอนกรีต', width: 1280, height: 960 },
      { src: '/images/speed-bump-job-10.webp', alt: 'ลูกระนาดยางมะตอยบริเวณทางเข้าออกหลังเก็บขอบ', width: 960, height: 1280 },
      { src: '/images/speed-bump-job-11.webp', alt: 'ทีมงานเกลี่ยยางมะตอยขึ้นรูปลูกระนาดบนพื้นคอนกรีต', width: 960, height: 1280 },
      { src: '/images/speed-bump-job-12.webp', alt: 'ลูกระนาดยางมะตอยหลังบดอัดและเครื่องตบอัดข้างแนวงาน', width: 960, height: 1280 },
      { src: '/images/speed-bump-job-13.webp', alt: 'ทีมงานใช้เครื่องตบอัดบดอัดลูกระนาดยางมะตอย', width: 960, height: 1280 },
    ],
  },
  {
    id: 'parking-marking', category: 'marking', title: 'งานตีเส้นจราจร',
    location: '', description: 'ตีเส้นช่องจอดรถ เส้นแบ่งช่องทาง และลูกศรบอกทิศทาง',
    siteTypes: 'ลานจอดรถและช่องทางเดินรถ',
    workScope: 'ตีเส้นช่องจอด เส้นขอบทาง และลูกศรบอกทิศทาง',
    images: [
      { src: '/images/projects-marking-cover.webp', alt: 'ภาพหน้างานตีเส้นจราจรและลูกศรบอกทิศทางหน้าอาคาร', width: 1280, height: 960 },
      { src: '/images/marking-job.webp', alt: 'ภาพหน้างานตีเส้นจราจร' },
      { src: '/images/marking-job-02.webp', alt: 'ช่องจอดรถสำหรับผู้ใช้รถเข็นและเส้นแบ่งพื้นที่' },
      { src: '/images/marking-job-03.webp', alt: 'งานตีเส้นช่องจอดรถตามแนวอาคาร' },
      { src: '/images/marking-job-04.webp', alt: 'ภาพรวมเส้นแบ่งช่องจอดรถข้างอาคาร' },
      { src: '/images/marking-job-05.webp', alt: 'งานตีเส้นช่องจอดรถและลูกศรจราจร' },
      { src: '/images/marking-job-06.webp', alt: 'ลูกศรบอกทิศทางและเส้นจราจรภายในอาคาร' },
      { src: '/images/marking-job-07.webp', alt: 'ทีมงานตีเส้นขอบทางด้วยเครื่องตีเส้น' },
      { src: '/images/marking-job-08.webp', alt: 'งานตีเส้นบริเวณทางโค้งและทางเข้าออก' },
      { src: '/images/marking-job-09.webp', alt: 'ทีมงานทำลูกศรบอกทิศทางจราจร' },
      { src: '/images/marking-job-10.webp', alt: 'เส้นแบ่งช่องทางและลูกศรภายในพื้นที่อาคาร' },
      { src: '/images/marking-job-11.webp', alt: 'งานตีเส้นแบ่งช่องทางเดินรถและลูกศรสองทิศทาง' },
      { src: '/images/marking-job-12.webp', alt: 'ทีมงานตีเส้นขอบทางโค้งบนพื้นคอนกรีต', width: 1280, height: 960 },
      { src: '/images/marking-job-13.webp', alt: 'เส้นขอบทางและแถบจราจรสีดำตามแนวอาคาร', width: 1280, height: 960 },
      { src: '/images/marking-job-14.webp', alt: 'งานตีเส้นและแถบจราจรบริเวณทางเข้าออกอาคาร', width: 1280, height: 960 },
      { src: '/images/marking-job-15.webp', alt: 'ภาพรวมเส้นขอบทางโค้งรอบลานจอดรถ', width: 1280, height: 960 },
    ],
  },
  {
    id: 'gravel-road', category: 'gravel', title: 'ถนนหินคลุก บดอัด',
    homepagePhoto: { src: '/images/home-gravel-road.webp', alt: 'ภาพหน้างานถนนหินคลุกบดอัดระหว่างอาคารระบบสาธารณูปโภค', width: 1280, height: 960 },
    location: '', description: 'เกลี่ยปรับระดับและบดอัดหินคลุกสำหรับถนนและทางเข้าออก',
    siteTypes: 'ถนนภายในพื้นที่อาคารและพื้นที่ติดตั้งแผงโซลาร์เซลล์',
    workScope: 'เกลี่ยปรับระดับและบดอัดถนนหินคลุก',
    images: [
      { src: '/images/gravel-road-job-04.webp', alt: 'ภาพหน้างานถนนหินคลุกบดอัดข้างอาคารสีน้ำเงิน', width: 1280, height: 720 },
      { src: '/images/gravel-road-job.webp', alt: 'ภาพหน้างานถนนหินคลุกขณะเกลี่ยและบดอัด' },
      { src: '/images/gravel-road-job-02.webp', alt: 'รถดันเกลี่ยหินคลุกและเตรียมพื้นถนน' },
      { src: '/images/gravel-road-job-03.webp', alt: 'งานเกลี่ยปรับระดับถนนหินคลุกข้างอาคาร' },
      { src: '/images/gravel-road-job-05.webp', alt: 'เครื่องจักรเกลี่ยหินคลุกบริเวณทางเข้าออก' },
      { src: '/images/gravel-road-job-06.webp', alt: 'ภาพแนวตั้งของถนนหินคลุกและเครื่องจักรขณะปรับระดับ' },
      { src: '/images/gravel-road-job-07.webp', alt: 'เครื่องจักรเกลี่ยและบดอัดถนนหินคลุกในภาพแนวตั้ง' },
      { src: '/images/gravel-road-job-08.webp', alt: 'รถบดบดอัดถนนหินคลุกข้างอาคาร' },
      { src: '/images/gravel-road-job-09.webp', alt: 'งานถนนหินคลุกบริเวณทางเข้าออกสู่ถนน' },
      { src: '/images/gravel-road-job-10.webp', alt: 'ภาพแนวตั้งของรถบดขณะบดอัดถนนหินคลุก' },
      { src: '/images/gravel-road-job-11.webp', alt: 'ภาพรวมถนนหินคลุกและรถบดขณะเก็บผิวทาง' },
      { src: '/images/gravel-road-job-12.webp', alt: 'รถดันและทีมงานเกลี่ยหินคลุกบริเวณทางเข้าออก' },
      { src: '/images/gravel-road-job-13.webp', alt: 'ภาพแนวตั้งของทีมงานและรถดันเกลี่ยถนนหินคลุก' },
      { src: '/images/gravel-road-job-14.webp', alt: 'รถบดบดอัดถนนหินคลุกในภาพแนวตั้ง' },
      { src: '/images/gravel-road-job-15.webp', alt: 'ภาพรวมถนนหินคลุกหลังบดอัดและรถบด' },
      { src: '/images/gravel-road-job-16.webp', alt: 'ภาพรวมถนนหินคลุกและรถบดบริเวณพื้นที่ติดตั้งแผงโซลาร์เซลล์', width: 1280, height: 960 },
      { src: '/images/gravel-road-job-17.webp', alt: 'ถนนหินคลุกบดอัดระหว่างอาคารระบบสาธารณูปโภคและถังน้ำ', width: 1280, height: 960 },
      { src: '/images/gravel-road-job-18.webp', alt: 'ผิวถนนหินคลุกบดอัดและรถบดบริเวณอาคารระบบสาธารณูปโภค', width: 1280, height: 960 },
      { src: '/images/gravel-road-job-19.webp', alt: 'รถบดบดอัดถนนหินคลุกระหว่างแนวเสาไฟฟ้าและอาคาร', width: 1280, height: 960 },
      { src: '/images/gravel-road-job-20.webp', alt: 'ภาพรวมถนนหินคลุกและรถบดระหว่างแนวแผงโซลาร์เซลล์', width: 1280, height: 960 },
    ],
  },
];
