// Generated by scripts/generate-responsive-photos.py; original photos are preserved.
export const responsivePhotos = {
  "/images/asphalt-job-01.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/asphalt-job-17.webp": {
    "originalWidth": 960,
    "widths": [
      480,
      800
    ]
  },
  "/images/asphalt-job-18.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/contact-asphalt.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/contact-gravel.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/contact-main.webp": {
    "originalWidth": 960,
    "widths": [
      480,
      800
    ]
  },
  "/images/contact-marking.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/gravel-job-14.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/gravel-road-job-04.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/hero-sharp.webp": {
    "originalWidth": 1536,
    "widths": [
      480,
      800
    ]
  },
  "/images/home-gravel-road.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/home-gravel-service.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/marking-home.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/marking-job.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/projects-gravel-cover.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/projects-marking-cover.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/projects-speed-bump-cover.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-asphalt.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-gravel-road.webp": {
    "originalWidth": 960,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-gravel.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-hero.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-marking.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/services-speed-bump.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/speed-bump-job-02.webp": {
    "originalWidth": 960,
    "widths": [
      480,
      800
    ]
  },
  "/images/speed-bump-job.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  },
  "/images/stone-home-01.webp": {
    "originalWidth": 960,
    "widths": [
      480,
      800
    ]
  },
  "/images/stone-job.webp": {
    "originalWidth": 1280,
    "widths": [
      480,
      800
    ]
  }
};

const escapeAttribute = value => String(value).replace(/[&<>"']/g, character => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[character]);

/**
 * Return optional HTML attributes for static cards and secondary page banners.
 * Keep the original src/width/height on the img; do not use this for lightboxes
 * or the homepage slider, which have their own full-photo behavior.
 */
export function responsivePhotoAttributes(src, sizes = '(min-width: 1304px) 580px, (min-width: 761px) calc((100vw - 96px) / 2), calc(100vw - 32px)', base = '/') {
  const photo = responsivePhotos[src];
  if (!photo) return '';
  const prefix = base.endsWith('/') ? base : `${base}/`;
  const stem = src.slice('/images/'.length).replace(/\.webp$/, '');
  const candidates = photo.widths.map(width => `${prefix}images/responsive/${stem}-${width}.webp ${width}w`);
  candidates.push(`${prefix}${src.replace(/^\//, '')} ${photo.originalWidth}w`);
  return `srcset="${escapeAttribute(candidates.join(', '))}" sizes="${escapeAttribute(sizes)}"`;
}
